"""empty message

Revision ID: ed202dd92732
Revises: 
Create Date: 2021-08-02 13:04:42.229215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed202dd92732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_area', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=400), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    op.drop_table('body')
    # ### end Alembic commands ###
